name: FireSwords
version: 1.1
main: main.FireSwords
description: Fun swords plugin
author: Hublot
depend: [ ProtocolLib ]
commands:
  getSword:
    usage: /getSword <Name> <Effects -> [ effect, effect... ]>
    description: Get your magic sword
    permission: fireswords.basic.getSwords